on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1

      - run: yarn

      - run: yarn build

      - name: Deploy Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: a67a0242-be41-4eee-9087-649aede4ef71
